import os
from dotenv import load_dotenv

load_dotenv()
AZURE_SEARCH_INDEX = "docs-index"
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_KEY = os.getenv("AZURE_SEARCH_KEY")
FORMRECOG_ENDPOINT = os.getenv("FORMRECOG_ENDPOINT")
FORMRECOG_APIKEY = os.getenv("FORMRECOG_APIKEY")

